# Generated by Django 3.2 on 2024-04-09 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20240409_1644'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite',
            field=models.ManyToManyField(related_name='in_favorite', through='users.UserFavoriteRecipe', to='recipes.Recipe', verbose_name='Рецепты в избранном'),
        ),
    ]
